# ==============================================================
# WAX CONFIGURATION
# ==============================================================
# Jekyll configuration files are written in YAML format.
# Colons, tabs/spacing, and quotes are meaningful in YAML.
# It is recommended you look at the following guide to avoid
# syntax errors in this file:
# ~> https://learnxinyminutes.com/docs/yaml/
#
#
# Questions ?
# ~> https://minicomp.github.io/wiki/#/
# ~> https://gitter.im/minicomp/wax/
#
# ---------------------------------------------------------------
# MAIN SETTINGS
# ---------------------------------------------------------------
# Feel free to change these! For more info, refer to:
# ~> https://jekyllrb.com/docs/configuration/options/

title:            'Atlantic Canada Species At Risk Modelling Data Catalogue'
description:      'A resource for Species At Risk model builders to find data they need and deposit data they create'
url:              'https://atlantichabitatmodels.github.io'
baseurl:          '/data'
copyright:        'Atlantic Canada Conservation Data Centre'
logo:             '/assets/logo.png'

# ---------------------------------------------------------------
# BUILD SETTINGS
# ---------------------------------------------------------------
# Best not to mess with these unless you know what you're doing!

permalink: 'pretty'
sass:
  style: compressed
exclude:
  - Gemfile*
  - Rakefile
  - vendor
  - spec
  - README.md
incremental: true
webrick:
  headers:
    'Access-Control-Allow-Origin': '*'
kramdown:
 auto_ids:       true
 footnote_nr:    1
 entity_output:  as_char
 footnote_backlink: "&#x21a9;&#xfe0e;"
 toc_levels:     1..6
 smart_quotes:   lsquo,rsquo,ldquo,rdquo
 enable_coderay: false


# --------------------------------------------------------------
# COLLECTION SETTINGS
# --------------------------------------------------------------
# Wax leverages Jekyll collections for much of its
# functionality, therefor some of the keys below are from
# Jekyll while others are Wax-specific.
# For more info, refer to:
# ~> https://jekyllrb.com/docs/collections/

collections:
  exhibits:
    output: true
  inputs: # name of collection
    output: true # makes sure pages are output as html files
    layout: 'data_item' # the layout for the pages to use
    metadata:
      source: 'data_input_catalog.csv' # path to the metadata file within `_data`
    images:
      source: 'raw_images/inputs' # path to the directory of images within `_data`

# --------------------------------------------------------------
# SEARCH INDEX SETTINGS
# --------------------------------------------------------------
# You can create multiple search indexes below (though only one is
# recommended!) by specifying
# an `index` file to write it to and some `collections` for it to index
# and running `$ bundle exec rake wax:search` .

search:
  main:
    index: '/search/index.json' # file the index will get written to
    collections:
      inputs:
        content: true # whether or not to index page content
        fields: # the metadata fields to index
          - pid
          - label
          - short_description
          - description
          - taxon_group
          - ecosystem_type
          - link
          - accessibility
          - contact_email
          - jurisdiction
          - spatial_data_type
          - keywords
          - data_product_type
          - cell_size
          - organization_individual
          - closed_consent_received
          - temporal_coverage

# --------------------------------------------------------------
# SITE MENU SETTINGS
# --------------------------------------------------------------
# Each menu item needs a `label` (whats shown), and a `link`
# (where it goes). An item can optionally have a dropdown
# submenu via `sub`.

menu:
  - label: 'Browse'
    link: '/catalogue/'
  - label: 'Search'
    link: '/search/'
  - label: 'Contribute'
    link: 'https://docs.google.com/spreadsheets/d/1_GZKDpZa18Ga0irokXhh-1ZUyF3TPi0Jl_yG4NrdVlk/edit#gid=1416728414'
  - label: By Province
    sub:
    - label: Nova Scotia
      link: '/nova-scotia/'
    - label: New Brunswick
      link: '/new-brunswick/'
    - label: Prince Edward Island
      link: '/prince-edward-island/'
  - label: 'Resources'
    sub:
    - label: 'Information to Include in a Data Request'
      link: '/requesting-data/'
    - label: 'Why is Data Sharing So Hard'
      link: '/data-sharing-challenges/'
    - label: 'Data Sharing Recommendations'
      link: '/data-sharing-recommendations/'      

# --------------------------------------------------------------
# SITE FOOTER SETTINGS
# --------------------------------------------------------------
#

footer:
  links:
    - label: 'GitHub'
      link: 'https://github.com/atlantichabitatmodels/data'
    - label: 'Credits'
      link: '/credits'
    - label: 'Contact'
      link: 'https://atlantichabitatmodels.github.io/communityofpractice/data-sharing-wg-team/'
    - label: 'Community of Practice'
      link: 'https://atlantichabitatmodels.github.io/communityofpractice/'
    - label: 'Report an Issue'
      link: 'https://github.com/atlantichabitatmodels/data/issues'
  logos:
    - img: '/img/logo.png'

# FIN
